site_name: EirSpace Documentation
theme:
  name: material
  features:
    - navigation.expand
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: static/logo.png
  favicon: static/favicon.ico
  font:
    text: "Space Grotesk"
    code: "JetBrains Mono"
plugins:
  - search
  - awesome-nav
extra_css:
  - styles/palette.css
  - styles/extra.css
extra_javascript:
  - styles/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
